# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red) "
use_symbol_for_status = true

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
show_sync_count = true
staged_count.enabled = true

[python]
format = 'via [${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
